services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: setup
    user: "0"
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    command: >
      sh -c '
      if [ ! -f /usr/share/elasticsearch/config/certs/elastic-certificate.p12 ]; then
        echo "Creating elastic-certificate.p12...";
        bin/elasticsearch-certutil cert --name elastic-certificate --days 365 --self-signed --out /usr/share/elasticsearch/config/certs/elastic-certificate.p12 --pass "";
        else
          echo "elastic-certificate.p12 already exists, skipping certificate creation.";
      fi;

      if [ ! -f /usr/share/elasticsearch/config/certs/instances.yml ]; then
        echo "Creating certs";
        echo -ne \
        "instances:\n"\
        "  - name: es01\n"\
        "    dns:\n"\
        "      - es01\n"\
        "      - localhost\n"\
        "    ip:\n"\
        "      - 127.0.0.1\n"\
        "  - name: kibana\n"\
        "    dns:\n"\
        "      - kibana\n"\
        "      - localhost\n"\
        "    ip:\n"\
        "      - 127.0.0.1\n"\
         > config/certs/instances.yml;
      fi;

      echo "Setting file permissions";
      find /usr/share/elasticsearch/config/certs -type d -exec chmod 750 \{\} \;;
      find /usr/share/elasticsearch/config/certs -type f -exec chmod 640 \{\} \;;
      tail -f /dev/null;
      '

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    restart: always
    command: /bin/sh -c "sleep 5 &&
      venv/bin/python manage.py makemigrations --noinput &&
      venv/bin/python manage.py migrate --noinput && 
      venv/bin/python manage.py collectstatic --noinput &&
      venv/bin/daphne -b 0.0.0.0 -p 8080 pong.asgi:application"
    volumes:
      - pong:/transcendence/pong
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - pong_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es01
    volumes:
      - certs:/usr/share/elasticsearch/config/certs:ro
    ports:
      - "9200:9200"
    networks:
      - app-network
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/elastic-certificate.p12
      - xpack.security.transport.ssl.keystore.type=PKCS12
      - xpack.security.transport.ssl.keystore.password=""
      - xpack.license.self_generated.type=${LICENSE}
    depends_on:
      - setup
      - logstash01
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'"]
      interval: 10s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    volumes:
      - certs:/usr/share/kibana/config/certs:ro
      - pong_kibana:/usr/share/kibana/data
    user: "1000:1000"
    ports:
      - 5601:5601
    networks:
      - app-network
    environment:
      - SERVERNAME=pong.kibana.org
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - es01
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"]
      interval: 10s
      timeout: 20s
      retries: 200
 
  logstash01:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: logstash01
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
    networks:
      - app-network
    environment:
      - ELASTIC_HOSTS=http://es01:9200
      - ELASTIC_USER=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.monitoring.enabled=false
      
volumes:
  certs:
    driver: local
  pong:
    driver: local
    driver_opts:
      type: none
      device: ${PROJECT_PATH}
      o: bind
  pong_pg_data:
    driver: local
  pong_es_data_01:
    driver: local
  pong_kibana:
    driver: local

networks:
  app-network:
    name: app-network
    driver: bridge



  #filebeat01:
  #depends_on:
  #- es01
  #  image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
  #  volumes:
  #    - certs:/usr/share/logstash/certs
  #    - pong_filebeat_data_01:/usr/share/filebeat/data
  #    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #    - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #  environment:
  #    - ELASTIC_USER=elastic
  #    - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  #    - ELASTIC_HOSTS=https://es01:9200
  #    - KIBANA_HOSTS=http://kibana:5601
  #    - LOGSTASH_HOSTS=http://logstash01:9600
  #    - xpack.monitoring.enabled=false
  #  networks:
  #    - app-network


