# Generated by Django 5.0.7 on 2024-07-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_tournoi',
        ),
        migrations.RemoveField(
            model_name='match',
            name='nbr_ball_touch_p1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='nbr_ball_touch_p2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournoi',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
    ]
