# Kibana's Elasticsearch URL
elasticsearch.hosts: ["https://es01:9200"]

# The name of the Kibana instance
server.name: "kibana"

# The base path for Kibana
#server.basePath: ""

# Serve the Kibana instance at the root path
#server.rewriteBasePath: false

# Enable or disable the Kibana server
server.enabled: true

# The port Kibana will listen on
server.port: 5601

# Enable or disable the xpack features
xpack.enabled: true

# Set the encryption key for encrypted saved objects
#xpack.encryptedSavedObjects.encryptionKey: ""

# Set the key for the kibana security features
#xpack.security.encryptionKey: ""

# Enable or disable the monitoring feature
xpack.monitoring.enabled: true

# Set the URL of the Elasticsearch instance to which Kibana should connect
#xpack.reporting.enabled: true

  #xpack.reporting.roles.enabled: false

# Enable the Kibana alerting feature
#xpack.alerting.enabled: false

# Enable or disable the usage collection
#xpack.usageCollection.enabled: true

# Configure the log level for Kibana
#logging.level: info

# Configure the directory where logs will be stored
logging.dest: /var/log/kibana/kibana.log

# Configure security and authentication settings
elasticsearch.username: test
elasticsearch.password: test 

# Disable or enable the Kibana plugin
#xpack.license.management.enabled: false

